schema {
  query: Query
  mutation: Mutation
}

scalar DateTime

enum Role {
  admin
  editor
  viewer
}

type User {
  id: ID!
  name: String!
  email: String!
  role: Role!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Project {
  id: ID!
  title: String!
  description: String
  price: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Category {
  id: ID!
  name: String!
}

type Location {
  id: ID!
  name: String!
}

type DashboardStats {
  totalProjects: Int!
  totalUsers: Int!
  totalRevenue: Int!
  averageProjectPrice: Float!
  maxProjectPrice: Int!
  recentProjectsCount: Int!
}


input ProjectInput {
  title: String!
  description: String
  price: Int
}

input CreateUserInput {
  name: String!
  email: String!
  password: String!
  role: Role!
}

input UpdateUserInput {
  name: String!
  email: String!
  role: Role!
}

type Query {
  users: [User!]!
  user(id: ID!): User
  projects: [Project!]!
  project(id: ID!): Project
  categories: [Category!]!
  locations: [Location!]!
  dashboardStats: DashboardStats!
}

type Mutation {
  createProject(input: ProjectInput!): Project!
  updateProject(id: ID!, input: ProjectInput!): Project!
  deleteProject(id: ID!): Project!
  createUser(input: CreateUserInput!): User!
  updateUser(id: ID!, input: UpdateUserInput!): User!
  deleteUser(id: ID!): User!
}
