schema {
  query: Query
  mutation: Mutation
}

scalar DateTime

enum Role {
  admin
  editor
  viewer
}

type User {
  id: ID!
  name: String!
  email: String!
  role: Role!
  createdAt: DateTime!
}

type Project {
  id: ID!
  title: String!
  description: String
  createdAt: DateTime!
  updatedAt: DateTime!
  price: Int
}

input ProjectInput {
  title: String!
  description: String
  price: Int
}

input UserInput {
  name: String!
  email: String!
  role: Role!
}

type Query {
  users: [User!]!
  user(id: ID!): User
  projects: [Project!]!
  project(id: ID!): Project
}

type Mutation {
  createProject(input: ProjectInput!): Project!
  updateProject(id: ID!, input: ProjectInput!): Project!
  deleteProject(id: ID!): Project!
  createUser(input: UserInput!): User!
  updateUser(id: ID!, input: UserInput!): User!
  deleteUser(id: ID!): User!
}
